import org.springframework.boot.SpringApplication

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
    static void main(String[] args) {
        SpringApplication.run Library, args
    }
}
